@baseUrl = http://localhost:3000
### Pesquisa todos os cursos
GET {{baseUrl}}/api/courses

### Cria uma nova conta
POST {{baseUrl}}/api/courses
Content-Type: application/json

{
"name": "Agronomia",
"description": "Curso Superior de Agronomia",
"url": "http://ifrs.edu.br/bento"
}

### Pesquisa curso específico
GET {{baseUrl}}/api/courses/65eca41d4ded0841ac55ec15

### Altera a conta com id=1
PUT {{baseUrl}}/api/courses/65eca41d4ded0841ac55ec15
Content-Type: application/json

{
"name": "Bacharel em Agronomia"
}

### Exclui uma conta específica
DELETE {{baseUrl}}/api/courses/65eca41d4ded0841ac55ec15